// .Language=English,English
//
enum
{
  MMenuString,           // "Coder Tools "
  MTitle,                // "Coder Tools"
  MComplete,             // "%d%% complete"
  MFound,                // "%d found"
  MWorking,              // "Processing data"
//
  MConfigMenu,           // "Coder Tools Setup"
  MConfig,               // "Coder Tools - Defaults"
//
  MSetMark,              // "Set current &mark"
  MSetMarkAdd,           // "Set &additional info"
  MSetProgInit,          // "Set programmers &initials"
  MSetReason,            // "Set &reason"
  MMarkSearch,           // "((BEGIN)|(END)|(DEL(ETE)?))"
  MMarkBegin,            // "BEGIN"
  MMarkEnd,              // "END"
  MMarkDelete,           // "DEL"
  MDebugBegin,           // "%s !!! Debug BEGIN %s"
  MDebugEnd,             // "%s !!! Debug END %s"
  MDefaultMark,          // "SIR 99999"
  MDefaultPattern,       // "SIR [0-9]{4,6}"
  MDefaultProgInit,      // "YOURSIG"
//
  MCTitle,               // "Customize language"
  MCBottom,              // "Ins,Del,F4"
  MLang,                 // "&Language"
  MTruncate,             // "Truncate trailnig &spaces and empty lines on file end"
  MCheckLongLines,       // "Check long lines when saving"
  MExpandTabs,           // "Expand TABs to spaces"
  MMask,                 // "&File mask"
  MOpenCmt,              // "&Openning comment"
  MCloseCmt,             // "&Closing comment"
  MOpenMark,             // "Openning mark
  MCloseMark,            // "Closing mark"
  MCloseAdd,             // "Closing add. mark"
  MSearchMarkReg,        // "Regexp mark pattern"
  MLeadingCmt,           // "Leading commen&t"
  MHeaderCmt,            // "&History line"
//
  MSelect,               // "Search result for \"%s\""
  MTotal,                // "Found %d line(s)"
  MRegError,             // "Invalid regular expression"
  MAll,                  // "All"
  MFoundLongLines,       // "Too long lines"
  MNoErrorsFound,        // "No errors found"
  MNoMarkFound,          // "No marks found"
//
  MOK,                   // "OK"
  MCancel,               // "Cancel"
  MError,                // "Error"
  MErrAlreadyOpened,     // "Already opened"
  MErrDeleteInside,      // "Cannot delete inside block"
  MErrClosedTwice,       // "Closed twice"
  MErrNotOpened,         // "Block is not opened"
  MErrNesting,           // "Wrong nesting"
  MErrContinuous,        // "Continuous block"
  MErrNoBlock,           // "This function can be used only when a block is selected!"
  MErrNoComment,         // "Line without leading comment found!"
  MErrNoMark,            // "No mark on this line!"
  MErrNoPairForDelete,   // "The DELETE trade mark has never a pair!"
  MErrNoPair,            // "Pair mark was not found!"
  MErrCurrentMarkSet,    // "No current mark set!"
//
  MMainMenu,             // "Coder Tools - Main Menu"
  MCommentBlock,         // "Comment block &>"
  MUncommentBlock,       // "Uncomment block &<"
  MMarkDebugBlock,       // "Mark debu&g block"
  MFindLongLines,        // "Find &too long lines"
  MSelectCurr,           // "&Select current change mark"
  MAddHistory,           // "Add modification &history"
  MDeleteBlk,            // "&Delete block"
  MMarkBlock,            // "Mark &block as changed"
  MFindPair,             // "&Find matching pair"
  MListCurr,             // "&List current change marks"
  MListErrors,           // "List &errorneous change marks"
  MListAll,              // "List &all change marks"
//
  MLongLineFound,        // "Too long lines were found when saving file!"
  MShow,                 // "Show now"
  MIgnoreToday,          // "Ignore today"
  MIgnoreForEver,        // "Ignore until manual check"
//
  MCDTitle,              // "Change dir"
  MCDLevelEdit,          // "Edit level"
  MCDBottom,             // "Ins,Del,F3 [Global],F4,Enter [User]"
  MCDUserName,           // "&User name"
  MCDNotAllowed,         // "Not allowed combination for this level/user!"
  MCDUnknownUser,        // "Unknown user"
  MCDUpdateUser,         // "Change disk for %s"
  MCDDesc,               // "&Description"
  MCDUserDisk,           // "User disk"
  MCDDir,                // "Di&rectory"
  MCDFmtUser,            // "&User format"
  MCDFmtGlobal,          // "&Global format"
//
//; Formatting of the history record, hardcoded for DBS
  MFmtDate,              // "%d-%b-%Y"
  MFmtHistory,           // "%s %s %-7.7s %-6.6s %-.50s"
  MFmtMarkOffset         // "4"
};
